### ISSUE TITLE
make -f Makefile in doris_core fails

### ISSUE THREAD

**Issue by Calcolatore** [TUDelftGeodesy/Doris#9]
When I lunch the `make -f Makefile` command, terminal return the following error and fails:
`bk_messages.hh:214:26: error: invalid conversion from ‘char’ to ‘const char*’ [-fpermissive]
         strcat(name_,'\0');// terminate id`
What can this error depend on? How I can solve it?

**Comment by avalentino** [comment]
Can you please provide more info about your environment: OS, compiler, etc?
If you are on linux the output of the following commands would be useful:

```
uname -a
lsb_release -a
g++ --version
```

**Comment by Calcolatore** [comment]
Here the command's returns:
`uname -a
Linux giovanni-VirtualBox 4.13.0-41-generic #46-Ubuntu SMP Wed May 2 13:38:30 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

g++ --version
g++ (Ubuntu 7.2.0-8ubuntu3.2) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

**Comment by avalentino** [comment]
OK, thanks.
I have a branch on my fork that fixes (also) this issue: https://github.com/avalentino/Doris/commits/debian-patches
In particular the relevant patch is the following: https://github.com/avalentino/Doris/commit/36782dbfb434fb82adabe1531eae8cf79886ea82.

Maybe you could give it a try.
